In [1]:
import pandas as pd
import datetime
import numpy as np
import re
import sys

sys.path.append("..")
from aoc18.utils import read_input
inp = read_input(10, root_path="..")
inp_test = read_input(10, test=True, root_path="..")

# Day 10

In [21]:
pattern = re.compile(r'=\<(.*),(.*)\> .*=\<(.*),(.*)\>')
li = pattern.findall('position=< -9,  1> velocity=< 0,  2>\n')[0]
points = 

-9 1 0 2


In [72]:
class Light:
    
    def __init__(self, x_0, y_0, v_x, v_y):
        self.position = np.array([x_0, y_0])
        self.speed = np.array([v_x, v_y])
        
    def get_position(self, seconds=0):
        return self.position + seconds * self.speed
    


class Sky:
    
    def __init__(self, lights=[]):
        self.lights = lights
    
    def add_point(self, point):
        self.lights.append(point)
        
    def get_boundaries(self, seconds=0):
        xs, ys = zip(*map(lambda light: light.get_position(seconds) , self.lights))
        return min(xs), min(ys), max(xs), max(ys)
        
    def show(self, seconds=0):
        min_x, min_y, max_x, max_y = self.get_boundaries(seconds)
        sky = np.zeros((max_y - min_y+1, max_x-min_x+1))
        for light in self.lights:
            pos_x, pos_y = light.get_position(seconds)
            sky[pos_y-min_y, pos_x-min_x] = 1
        for line in sky:
            print("".join(map(lambda x: "." if x==0 else "#", line)))    
    

In [73]:
lights_test = map(lambda line: Light(*map(int, pattern.findall(line)[0])), inp_test)
sky_test = Sky(list(lights_test))

lights = map(lambda line: Light(*map(int, pattern.findall(line)[0])), inp)
sky = Sky(list(lights))

In [84]:
def run_1(inp):
    mx, my, Mx, My = sky.get_boundaries(0)
    widths = [Mx-mx]
    heights = [My-my]
    second = 1
    while True:
        mx, my, Mx, My = sky.get_boundaries(second)
        width = Mx - mx
        height = My - my
        widths.append(width)
        heights.append(height)
        if width > widths[-2] or height > heights[-2]:
            break
        second+=1
    second = second-1
    print("ANSWER 1 : ")
    sky.show(second)
    print("ANSWER 2 : ")
    print("Message will be shown after %d seconds" % second)

In [85]:
run_1(inp)

ANSWER 1 : 
#....#..#####...#....#..######..######..#....#...####......###
##...#..#....#..#....#..#............#..#....#..#....#......#.
##...#..#....#..#....#..#............#..#....#..#...........#.
#.#..#..#....#..#....#..#...........#...#....#..#...........#.
#.#..#..#####...######..#####......#....######..#...........#.
#..#.#..#....#..#....#..#.........#.....#....#..#...........#.
#..#.#..#....#..#....#..#........#......#....#..#...........#.
#...##..#....#..#....#..#.......#.......#....#..#.......#...#.
#...##..#....#..#....#..#.......#.......#....#..#....#..#...#.
#....#..#####...#....#..######..######..#....#...####....###..
ANSWER 2 : 
Message will be shown after 10558 seconds


In [78]:
second-1

10558

# Day 11

In [35]:
import itertools
import time

In [20]:
inp = 2568
inp_test = 18

def fuel_level(x, y, inp=inp):
    rack_id = x + 10
    return (((rack_id * y + inp) * rack_id) % 1000) // 100 - 5
    

In [30]:
size = 300
sub_grid = 3
grid_coordinates = itertools.product(range(size), range(size))
grid = np.zeros((size, size))
for x, y in grid_coordinates:
    grid[x, y] = fuel_level(x, y, inp=inp)
max_total = 0
answer = (0, 0) 
for x, y in itertools.product(range(size - sub_grid), range(size - sub_grid)):
    this_sub_grid_total = grid[x: x+sub_grid, y: y+sub_grid].sum()
    if max_total < this_sub_grid_total:
        max_total = this_sub_grid_total
        answer = (x, y)
print(answer)

(21, 68)


In [32]:
cache = np.zeros((size, size, size))
cache[:,:,1] = grid

def get_sub_total(x, y, s):
    global cache
    if s==1:
        return cache[x, y, 1]
    else:
        new_total = cache[x, y, s-1] + grid[x+s, y:y+s-1].sum() + grid[x:x+s, y+s].sum()
        cache[x, y, s] = new_total
        return new_total

In [36]:
st = time.time()
max_total = 0
answer = (0, 0, 1)
for sub_grid in range(1, size):
    for x, y in itertools.product(range(size - sub_grid), range(size - sub_grid)):
        this_sub_grid_total = get_sub_total(x, y, sub_grid)
        if max_total < this_sub_grid_total:
            max_total = this_sub_grid_total
            answer = (x, y, sub_grid+1)
print(answer)
print("found in %s seconds" % (time.time() - st))

(90, 201, 14)
found in 65.42646718025208 seconds


In [37]:
st = time.time()
max_total = 0
answer = (0, 0, 1)
for sub_grid in range(1, size):
    for x, y in itertools.product(range(size - sub_grid), range(size - sub_grid)):
        this_sub_grid_total = grid[x: x+sub_grid, y: y+sub_grid].sum()
        if max_total < this_sub_grid_total:
            max_total = this_sub_grid_total
            answer = (x, y, sub_grid)
print(answer)
print("found in %s seconds" % (time.time() - st))

(90, 201, 15)
found in 152.98023629188538 seconds


# DAY 12

In [3]:
inp = read_input(12, root_path="..")

In [14]:
str_to_int = lambda x: 1 if x=="#" else 0
inital_state = np.array(list(map(str_to_int, inp[0].strip().split(": ")[-1])))
inital_state

array([1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1,
       1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1,
       0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0,
       0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1,
       1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1])

In [15]:
def interpret_rule(line):
    line = line.strip()
    match, result = line.split(" => ")
    match = np.array(list(map(str_to_int, match)))
    result = str_to_int(result)
    return match, result

rules = list(map(interpret_rule, inp[2:]))

In [16]:
rules[0]

(array([1, 1, 0, 0, 0]), 0)